//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNT_DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class comprobantePago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comprobantePago()
        {
            this.detalleComprobante = new HashSet<detalleComprobante>();
            this.venta = new HashSet<venta>();
        }
    
        public int idComprobante { get; set; }
        public string nroComprobante { get; set; }
        public Nullable<int> idTipoComprobante { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<double> igv { get; set; }
        public Nullable<double> total { get; set; }
        public int idTipoPago { get; set; }
        public Nullable<double> descuento { get; set; }
        public string usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string guid_comprobante { get; set; }
    
        public virtual tipoComprobante tipoComprobante { get; set; }
        public virtual tipoPago tipoPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleComprobante> detalleComprobante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venta> venta { get; set; }
    }
}
