//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNT_DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public int idVenta { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idEmpleado { get; set; }
        public Nullable<int> idComprobante { get; set; }
        public string observacion { get; set; }
        public string usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual comprobantePago comprobantePago { get; set; }
        public virtual empleado empleado { get; set; }
    }
}
